version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: myapp-backend
    ports:
      - "5028:8000"
    
    environment:
      - ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=sqlite:///./app.db
    env_file:
      - .env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: myapp-frontend
    ports:
      - "5029:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://myapp-backend:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend